version: '3.4'

services:
  crash-redis:
    build:
      context: .
      dockerfile: dockerfiles/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server --loadmodule /usr/lib/redisgraph.so
    ports:
      - '16379:6379'

  crash-service:
    build:
      context: .
      dockerfile: dockerfiles/service
    depends_on:
      - crash-redis
    networks:
      default:
        aliases:
          - service
